# Generated by Django 3.1.5 on 2021-01-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='tags',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='uploaded_by',
            field=models.CharField(default='default_', max_length=50),
            preserve_default=False,
        ),
    ]
