# Generated by Django 3.1.5 on 2021-01-07 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210107_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shop',
            name='photo',
            field=models.ImageField(upload_to='shop'),
        ),
    ]
