# Generated by Django 3.1.5 on 2021-01-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210107_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='name',
        ),
    ]
